mongo:
  host:     localhost
  port:     27017
  db:       katharsis
  user:
  password:

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

logging:
  level: INFO

  appenders:
    - type: console